# Generated by Django 4.2.9 on 2024-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=50, verbose_name='Book_name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='price')),
            ],
        ),
    ]
