# Generated by Django 4.2.9 on 2024-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=11, verbose_name='Name'),
        ),
    ]
