# Generated by Django 4.2.9 on 2024-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_author_remove_book_age_remove_book_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='mark_price'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(default=' ', max_length=50, verbose_name='Public'),
        ),
    ]
